# Generated by Django 4.1 on 2022-12-08 16:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_date', models.DateTimeField()),
                ('total_price', models.PositiveBigIntegerField()),
                ('total_product', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_num', models.PositiveSmallIntegerField()),
                ('history_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.history')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.product')),
            ],
        ),
    ]
